//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDCarDealership_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int VehicleID { get; set; }
        public Nullable<decimal> Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<int> MakeID { get; set; }
        public Nullable<int> VehicleModelID { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
    }
}
